---
- name: run cli command pre hook
  include_tasks: "{{ iosxr_run_cli_command_pre_hook }}"
  when: iosxr_run_cli_command_pre_hook is defined and iosxr_run_cli_command_pre_hook

- name: run command and parse output
  cli:
    command: "{{ iosxr_command }}"
    parser: "{{ parser }}"
    engine: "{{ iosxr_parser_engine | default(None) }}"
  with_first_found:
    - files:
        - "{{ iosxr_parser }}"
      paths:
        - "{{ playbook_dir }}/parser_templates/iosxr"
        - "~/.ansible/ansible_network/parser_templates/iosxr"
        - "/etc/ansible/ansible_network/parser_templates/iosxr"
        - "{{ role_path }}/parser_templates"
  loop_control:
    loop_var: parser

- name: run cli command post hook
  include_tasks: "{{ iosxr_run_cli_command_post_hook }}"
  when: iosxr_run_cli_command_post_hook is defined and iosxr_run_cli_command_post_hook
